/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  MigratableCounter,
  MigratableCounterInterface,
} from "../MigratableCounter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "initialValue",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "Incremented",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "ValueSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "by",
        type: "uint256",
      },
    ],
    name: "increment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "value",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161027738038061027783398101604081905261002f91610049565b600080546001600160a01b03191633179055600155610062565b60006020828403121561005b57600080fd5b5051919050565b610206806100716000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80633fa4f24514610051578063552410771461006d5780637cf5dab0146100825780638da5cb5b14610095575b600080fd5b61005a60015481565b6040519081526020015b60405180910390f35b61008061007b366004610190565b6100c0565b005b610080610090366004610190565b610146565b6000546100a8906001600160a01b031681565b6040516001600160a01b039091168152602001610064565b6000546001600160a01b0316331461010a5760405162461bcd60e51b81526020600482015260096024820152682727aa2fa7aba722a960b91b604482015260640160405180910390fd5b60018190556040518181527f012c78e2b84325878b1bd9d250d772cfe5bda7722d795f45036fa5e1e6e303fc906020015b60405180910390a150565b806001600082825461015891906101a9565b90915550506001546040519081527f20d8a6f5a693f9d1d627a598e8820f7a55ee74c183aa8f1a30e8d4e8dd9a8d849060200161013b565b6000602082840312156101a257600080fd5b5035919050565b808201808211156101ca57634e487b7160e01b600052601160045260246000fd5b9291505056fea264697066735822122040d86e4c193b0f9457d01a85a6f79666244621425f8abecf1717f4db2830cdb464736f6c63430008180033";

type MigratableCounterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MigratableCounterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MigratableCounter__factory extends ContractFactory {
  constructor(...args: MigratableCounterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    initialValue: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(initialValue, overrides || {});
  }
  override deploy(
    initialValue: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(initialValue, overrides || {}) as Promise<
      MigratableCounter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MigratableCounter__factory {
    return super.connect(runner) as MigratableCounter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MigratableCounterInterface {
    return new Interface(_abi) as MigratableCounterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MigratableCounter {
    return new Contract(address, _abi, runner) as unknown as MigratableCounter;
  }
}
